### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by Pana** [arusanov/avatar-generator#2]
osx 10.9
node 0.10  0.12
iojs 1.6.4 
all have this error 

```
npm ERR! Error: ENOENT, chmod '/Users/pana/projects/node_modules/avatar-generator/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/pana/.nvm/v0.10.35/bin/node" "/Users/pana/.nvm/v0.10.35/bin/npm" "install" "avatar-generator"
npm ERR! cwd /Users/pana/projects
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /Users/pana/projects/node_modules/avatar-generator/cli.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0
```

**Comment by arusanov** [comment]
Can you try again? I've updated npm packeage. Now it should be ok.
```
avatar-generator@1.0.6 node_modules/avatar-generator
├── seed-random@2.2.0
├── through@2.3.8
├── underscore@1.8.3
└── commander@2.8.1 (graceful-readlink@1.0.1)
```

**Comment by ssymbol** [comment]
I was trying to use your library in ec2 amazon server, but having some issues, I have a suspect that this library might be related to that, any ideas?

Trace on requesting an image:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

I am pretty sure it is becase of it, since I am trying to fetch image and it fails...
Any folder permissions or libraries on OS?
